title:
name:
email: enquiries@10xeducation.com.au
description: >- # this means to ignore newlines until "baseurl:"
    HSC Software Engineering & Enterprise Computing Tutoring
baseurl: '/10xEducation' # the subpath of your site, e.g. /blog
url: 'https://muscat.sh/' # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:
github_username:

theme: minima
show_downloads: false
github:
    is_project_page: false
markup:
    goldmark:
        renderer:
            unsafe: true
minima:
    skin: dark
